print("Digite seu nome: ")
entrada = input()
print(entrada)
print("\n")
nome = input("Digite seu nome: ")
print(nome)
print("Seu nome é %s." %nome)
print("\n")
idade = input("Digite sua idade: ")
idadeInt = int(idade)
idadeFloat = float(idade)
print(type(idade))
print(type(idadeInt))
print(type(idadeFloat))
print("\n")
idade = int(input("Digite sua idade: "))
valor = float(input("Digite o valor das propinas: "))
print(type(idade))
print(type(valor))
