nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade atual: "))
ano = int(input("Digite o ano atual: "))
print(nome + ", em 2025 você terá " + str(idade + (2025 - ano)) + " anos.")
print("%s, em 2025 você terá %d anos." %(nome, (idade + (2025 - ano))))
